<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE applications [
<!ELEMENT applications (group)+>
<!ELEMENT group (name , application+)>
<!ELEMENT application (name , code+ , input* , output+)>
<!ELEMENT input (name , type , desc , hint?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT code (#PCDATA)>
<!ELEMENT output (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT desc (#PCDATA)>
<!ELEMENT hint (#PCDATA)>
]>
<applications>

	<group>

		<name>Ordinamento</name>

		<application>
			<name>A bolle</name>
			<code>sort/prim.js</code>
			<code>sort/bubble.js</code>
			<input>
				<name>n</name>
				<type>int</type>
				<desc>Numero di elementi</desc>
			</input>
			<output>text</output>
		</application>

		<application>
			<name>Per selezione</name>
			<code>sort/prim.js</code>
			<code>sort/prim-selection.js</code>
			<code>sort/selection.js</code>
			<input>
				<name>n</name>
				<type>int</type>
				<desc>Numero di elementi</desc>
			</input>
			<output>text</output>
		</application>

		<application>
			<name>Per fusione</name>
			<code>sort/prim.js</code>
			<code>sort/prim-merge.js</code>
			<code>sort/merge.js</code>
			<input>
				<name>n</name>
				<type>int</type>
				<desc>Numero di elementi</desc>
			</input>
			<output>text</output>
		</application>

	</group>
	
	<group>

		<name>Prestazioni ordinamento</name>

		<application>
			<name>Numero di confronti</name>
			<code>sort/prim.js</code>
			<code>sort/bubble.js</code>
			<code>sort/prim-selection.js</code>
			<code>sort/selection.js</code>
			<code>sort/prim-merge.js</code>
			<code>sort/merge.js</code>
			<code>sort/confronti.js</code>
			<input>
				<name>n</name>
				<type>int</type>
				<desc>Numero di prove</desc>
			</input>
			<output>chart</output>
		</application>

		<application>
			<name>Numero di scambi</name>
			<code>sort/prim.js</code>
			<code>sort/bubble.js</code>
			<code>sort/prim-selection.js</code>
			<code>sort/selection.js</code>
			<code>sort/prim-merge.js</code>
			<code>sort/merge.js</code>
			<code>sort/scambi.js</code>
			<input>
				<name>n</name>
				<type>int</type>
				<desc>Numero di prove</desc>
			</input>
			<output>chart</output>
		</application>

		<application>
			<name>Cronometro</name>
			<code>sort/prim.js</code>
			<code>sort/bubble.js</code>
			<code>sort/prim-selection.js</code>
			<code>sort/selection.js</code>
			<code>sort/prim-merge.js</code>
			<code>sort/merge.js</code>
			<code>sort/cronometro.js</code>
			<input>
				<name>n</name>
				<type>int</type>
				<desc>Numero di prove</desc>
			</input>
			<output>chart</output>
		</application>

	</group>

	<group>

		<name>Mappe</name>

		<application>
			<name>Mappa</name>
			<code>map/mappa.js</code>
			<output>map</output>
		</application>

		<application>
			<name>Marker</name>
			<code>map/marker.js</code>
			<input>
				<name>lat</name>
				<type>float</type>
				<desc>Latitudine</desc>
				<hint>Prova con 45.477822</hint>
			</input>
			<input>
				<name>lng</name>
				<type>float</type>
				<desc>Longitudine</desc>
				<hint>Prova con 9.169501</hint>
			</input>
			<output>map</output>
		</application>

		<application>
			<name>Operazioni con le distanze</name>
			<code>map/coord.js</code>
			<input>
				<name>lat0</name>
				<type>float</type>
				<desc>Latitudine primo punto</desc>
			</input>
			<input>
				<name>lng0</name>
				<type>float</type>
				<desc>Longitudine primo punto</desc>
			</input>
			<input>
				<name>lat1</name>
				<type>float</type>
				<desc>Latitudine secondo punto</desc>
			</input>
			<input>
				<name>lng1</name>
				<type>float</type>
				<desc>Longitudine secondo punto</desc>
			</input>
			<output>text</output>
		</application>

		<application>
			<name>Distanza da un punto</name>
			<code>map/coord.js</code>
			<code>map/semplice-dist.js</code>
			<output>map</output>
		</application>

		<application>
			<name>I dieci pi√π vicini</name>
			<code>sort/prim.js</code>
			<code>sort/prim-merge.js</code>
			<code>sort/merge.js</code>
			<code>map/coord.js</code>
			<code>map/diecipunti.js</code>
			<input>
				<name>lat</name>
				<type>float</type>
				<desc>Latitudine</desc>
				<hint>Prova con 45.477822</hint>
			</input>
			<input>
				<name>lng</name>
				<type>float</type>
				<desc>Longitudine</desc>
				<hint>Prova con 9.169501</hint>
			</input>
			<input>
				<name>n</name>
				<type>int</type>
				<desc>Quanti punti</desc>
			</input>
			<output>map</output>
		</application>

		<application>
			<name>Inviluppo convesso</name>
			<code>sort/prim.js</code>
			<code>sort/prim-merge.js</code>
			<code>sort/merge.js</code>
			<code>map/convexhull-prim.js</code>
			<code>map/convexhull.js</code>
			<input>
				<name>n</name>
				<type>int</type>
				<desc>Quanti punti</desc>
			</input>
			<output>map</output>
		</application>

	</group>

	<group>

		<name>Sicurezza</name>

		<application>
			<name>Diffie-Hellman</name>
			<code>security/diffie.js</code>
			<input>
				<name>p</name>
				<type>int</type>
				<desc>Numero primo</desc>
			</input>
			<input>
				<name>n</name>
				<type>int</type>
				<desc>Base</desc>
			</input>
			<input>
				<name>x</name>
				<type>int</type>
				<desc>Segreto di Alice</desc>
			</input>
			<input>
				<name>y</name>
				<type>int</type>
				<desc>Segreto di Bruno</desc>
			</input>
			<output>text</output>
		</application>

		<application>
			<name>Indovina la password 1</name>
			<code>security/password.js</code> 
                        <code>security/checkpwd-simple.js</code>
			<input>
				<name>pwd</name>
				<type>text</type>
				<desc>Password</desc>
			</input>
			<output>text</output>
</application>

		<application>
			<name>Indovina la password 2</name>
			<code>security/password-hash.js</code> 
                        <code>security/checkpwd-hash.js</code>
			<input>
				<name>pwd</name>
				<type>text</type>
				<desc>Password</desc>
			</input>
			<output>text</output>
</application>

		<application>
			<name>Indovina la password 3</name>
			<code>security/password-shash.js</code> 
                        <code>security/checkpwd-shash.js</code>
			<input>
				<name>pwd</name>
				<type>text</type>
				<desc>Password</desc>
			</input>
			<output>text</output>
</application>

		<application>
			<name>Privacy</name>
			<code>security/privacy.js</code> 
			<input>
				<name>lat1</name>
				<type>float</type>
				<desc>Latitudine primo punto</desc>
			</input>
			<input>
				<name>lng1</name>
				<type>float</type>
				<desc>Longitudine primo punto</desc>
			</input>
			<input>

				<name>d1</name>
				<type>float</type>
				<desc>Distanza primo punto</desc>
			</input>
			<input>
				<name>lat2</name>
				<type>float</type>
				<desc>Latitudine secondo punto</desc>
			</input>
			<input>
				<name>lng2</name>
				<type>float</type>
				<desc>Longitudine secondo punto</desc>
			</input>
			<input>

				<name>d2</name>
				<type>float</type>
				<desc>Distanza secondo punto</desc>
			</input>
			<input>
				<name>lat3</name>
				<type>float</type>
				<desc>Latitudine terzo punto</desc>
			</input>
			<input>
				<name>lng3</name>
				<type>float</type>
				<desc>Longitudine terzo punto</desc>
			</input>
			<input>

				<name>d3</name>
				<type>float</type>
				<desc>Distanza terzo punto</desc>
			</input>

			<output>text</output>
</application>


       </group>


	<group>

		<name>Varie</name>

		<application>
			<name>Playground</name>
			<code>misc/play.js</code>
			<input>
				<name>n</name>
				<type>inr</type>
				<desc>Numero intero</desc>
			</input>
			<input>
				<name>f</name>
				<type>fload</type>
				<desc>Numero reale</desc>
			</input>
			<input>
				<name>s</name>
				<type>string</type>
				<desc>Parole</desc>
			</input>
			<output>text</output>
		</application>

		<application>
			<name>Colori</name>
			<code>misc/color.js</code>
			<output>text</output>
		</application>

		<application>
			<name>Somma</name>
			<code>misc/somma.js</code>
			<input>
				<name>i0</name>
				<type>int</type>
				<desc>Primo addendo</desc>
				<hint>Un numero, ad esempio 3</hint>
			</input>
			<input>
				<name>i1</name>
				<type>int</type>
				<desc>Secondo addendo</desc>
				<hint>Un numnero, ad esempio 5</hint>
			</input>
			<input>
				<name>s0</name>
				<type>string</type>
				<desc>Prima parola</desc>
				<hint>Una parola, ad esempio "ciao"</hint>
			</input>
			<input>
				<name>s1</name>
				<type>string</type>
				<desc>Seconda parola</desc>
				<hint>Una parola, ad esempio "mamma"</hint>
			</input>
			<output>text</output>
		</application>

		<application>
			<name>Grafico</name>
			<code>misc/chart.js</code>
			<input>
				<name>n</name>
				<type>int</type>
				<desc>Numero di punti</desc>
			</input>
			<output>chart</output>
		</application>
	
	</group>
	
</applications>
